### ISSUE TITLE
Cannot find module 'immutable'

### ISSUE THREAD

**Issue by sergio11** [altjs/utils#16]
Hi there,
I always get the following error when using the module ImmutableUtil

`[21:12:50] Error: Cannot find module 'immutable' from 'C:\Users\Sergio\lik\node_modules\alt-utils\lib'`

I installed successfully dependence and I'm using as follows:

```
import alt from '../alt';
import AppActions from '../actions/AppActions';
import immutable from 'alt-utils/lib/ImmutableUtil';
```

`
export default alt.createStore(immutable(AppStore));`

can they help me?
tanks and greetings.

**Comment by goatslacker** [comment]
`npm install immutable`

**Comment by xxRockOnxx** [comment]
> npm install immutable

doing that returned me this:

`Cannot find module 'alt/utils/ImmutableUtil'immutable@3.8.1 node_modules/immutable`

it's not even there. It's on

`alt-utils/lib/ImmutableUtils`

I just followed your guide. You might need to do some updates now @goatslacker
