### ISSUE TITLE
`index.js` is missing from distribution version?

### ISSUE THREAD

**Issue by bebraw** [altjs/utils#7]
_package.json_ seems to point at _index.js_ at the package root using `"main": "index.js",`. This breaks the package for me at least as it's looking for a non-existent entry point.

**Comment by goatslacker** [comment]
This is on purpose. Is it preventing you from doing `import AltManager from 'alt-utils/lib/AltManager';`?

**Comment by bebraw** [comment]
Nope. This will work just fine.

The interface is just a little different than what I'm used to. :+1:
